/* Write your PL/SQL query statement below */
SELECT S.NAME
FROM SALESPERSON S
WHERE S.SALES_ID
NOT IN (
    SELECT O.SALES_ID
    FROM COMPANY C
    INNER JOIN ORDERS O
    ON O.COM_ID = C.COM_ID
    WHERE C.NAME = 'RED'
)